config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'portfolios#index'
  
  # ログインページの表示・ログイン判別・ログアウト
  get ENV['LOGIN_URL'], to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  # 記事関係
  resources :articles
  
  # カテゴリ関係
  resources :categories, :only => [:new, :create, :destroy]
  
  # ユーザー関係
  # なし
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

  # ここで設定したカラムをfile_fieldメソッドで呼び出せば，
  # store_dirに保存される
  mount_uploader :image, ArticleUploader
  

  validates :title, presence: true, length: { maximum: 50 }
  validates :content, presence: true
  validates :image, presence: true
  
  belongs_to :user
  belongs_to :category, optional: true
end

app/models/category.rb
class Category < ApplicationRecord
  
  validates :name, presence: true, uniqueness: { case_sensitive: false }
  
  has_many :articles
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :articles, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  # current_userへの代入やcurrent_userに値があるかを判断するメソッドをインクルード
  include SessionsHelper
  
  private
  
  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  

  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :admin_user?, only: [:new,:edit,:destroy]
  before_action :article_find_id, only: [:show, :edit, :update, :destroy]
  before_action :category_all, only: [:index, :new, :create, :edit, :update]
  
  def index
    if params[:current_category]
      if params[:current_category] === "Unselected"
        @articles = Article.where(category_id: nil).order(title: "asc").page(params[:page]).per(7) # カテゴリ未定義のものを選択
      else
        @articles = Article.where(category_id: params[:current_category]).order(title: "asc").page(params[:page]).per(7) # 既存カテゴリを選択
      end
    else
      @articles = Article.all.order(title: "asc").page(params[:page]).per(7) # すべてのカテゴリを取得
    end
  end
  
  def show
  end
  
  def new
    @article = current_user.articles.build()
  end
  
  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      flash[:success] = '記事を作成しました'
      redirect_to articles_url
    else
      flash.now[:danger] = '記事作成に失敗しました'
      render :new
    end
  end
  
  def edit
    puts "(。-`ω-)"
    puts @article.content
  end
  
  def update
    if @article.update(article_params)
      flash[:success] = '記事を編集しました'
      redirect_to article_path(@article)
    else
      flash.now[:danger] = '記事編集に失敗しました'
      render :edit
    end
  end
  
  def destroy
    @article.destroy
    flash[:success] = '記事を削除しました'
    redirect_back(fallback_location: root_path)
  end
  
  private
  
  def article_params
    params.require(:article).permit(:category_id, :image, :title, :content)
  end
  
  def article_find_id
    @article = Article.find(params[:id])
  end
  
  def category_all
    @categories = Category.all.order(name: "asc")
  end
  
  def admin_user?
    if !logged_in?
      flash[:danger] = '管理者のみ編集や退会が行えます'
      redirect_back(fallback_location: articles_url)
    end
  end
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :admin_user?, only: [:new, :destroy]
  
  def new
    @category = Category.new()
  end
  
  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "カテゴリを新規作成しました"
      redirect_to articles_path
    else
      flash.now[:danger] = Category 
      render :new
    end
  end
  
  def destroy
    @category = Category.find(params[:id])
    
    @category.articles.update_all(category_id: nil)
    
    @category.destroy
    flash[:success] = "削除に成功しました"
    redirect_to articles_path
  end
  
  private
  
  def category_params
    params.require(:category).permit(:name)
  end
  
  def admin_user?
    if !logged_in?
      flash[:danger] = '管理者のみ新規作成・編集・退会が行えます'
      redirect_back(fallback_location: articles_url)
    end
  end
  
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  def index
    
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if current_user
      redirect_to articles_url
    end
  end

  def create
    # paramsに入っている:sessionのデータからメールの情報を取り，すべて小文字化
    email = params[:session][:email].downcase
    # paramsに入っている:sessionのデータからパスワードの情報をとる
    password = params[:session][:password]
    
    # ログイン判定後処理
    if login(email, password)
      flash[:success] = 'ログインに成功しました'
      redirect_to articles_url
    else
      flash[:danger] = 'ログインに失敗しました'
      redirect_to articles_url
    end
    
    
    
  end

  def destroy
    session[:user_id] = nil
    flash.now[:success] = 'ログアウトしました'
    redirect_to articles_url
  end
  
  private
  
  # ログイン処理
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  require "redcarpet"

  def markdown(text)
      options = {
          filter_html:     true,
          hard_wrap:       true,
          space_after_headers: true
      }

      extensions = {
          autolink: true,
          fenced_code_blocks: true,
          lax_spacing: true,
          no_intra_emphasis: true,
          strikethrough: true,
          superscript: true,
          tables: true
      }
      renderer = Redcarpet::Render::HTML.new(options)
      @markdown = Redcarpet::Markdown.new(renderer, extensions)
    @markdown.render(text).html_safe
  end
  
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
  
end

app/views/articles/edit.html.erb
<!-- articles/edit.html.erb -->
<%= form_with(model: @article, local: true) do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>
  
  <div class="form-group">
    <div class="container">
      <div id='editor'>
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <%= f.label :category_id, "カテゴリ" %>
              <%= f.collection_select(:category_id, @categories, :id, :name, :include_blank => "-未分類-") %>
            </div>
            
            <div class="form-group">
              <%= f.label :image, 'アイキャッチ画像' %>
              <%= f.file_field :image %>
            </div>
            
            <div class="form-group">
              <%= f.label :title, '記事タイトル' %>
              <%= f.text_field :title %>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6">
            <%= f.label :content, 'コンテンツ' %>
            <%= f.text_area :content, rows: 20, class: 'form-control', "v-model" => "input", name: "article[content]" %>
            
          </div>
          <div class="col-md-6">
            <div id="preview-field" class="content markdown-field" v-html="convertMarkdown"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  
  <%= link_to '記事一覧ページに戻る', articles_path, class: 'btn btn-secondary' %>
  <%= f.submit '記事更新', class: 'btn btn-primary' %>
  
<% end %>

<script>
  $(document).on('turbolinks:load', function() {
    
    // リアルタイムプレビュー
    new Vue({
      el: '#editor',// index.htmlでid="editor"となっている要素（エレメント）を指定
      data: {
        // index.htmlでv-model="input"が付与されている要素と双方向データバインディングされている。
        input: document.querySelector("[v-model='input']").value, 
      },
      computed: {
        convertMarkdown: function() {
          // index.htmlでv-html="convertMarkdown"が付与されている要素（エレメント）とバインディングされている。
          // 入力されたデータをHTMLに変換して表示させる。
          return marked(this.input);
        }
      }
    });
    
  });
</script>

app/views/articles/index.html.erb
<!-- articles/index.html.erb -->
<div class="container w-100">
  <div class="row">
    <!--カテゴリ選択-->
    <div class="col-md-3 select-category">
      <div class="profile-image mb-3">
        <!--<img src="/komugiko.png" alt="プロフィール画像" class="img-fluid">-->
        <%= image_tag('komugiko.png')%>
        <h5 class="text-center">admin: komugiko</h5>
        <p>プログラミングの勉強過程での備忘録として，ブログをつけていこうと思います．</p>
      </div>
      <ul class="list-group">

        <%= link_to "All", articles_path, class: "list-group-item list-group-item-action" %>


        <% @categories.each do |category| %>

            <%= link_to category.name, articles_path(current_category: category.id), class: "list-group-item list-group-item-action" %>
            <% if logged_in? %>
              <%= link_to category, method: :delete, class: "ml-1 delete-icon", data: { confirm: '本当に削除してよろしいですか?' } do %>
                <i class="fa fa-trash"></i>
              <% end %>
            <% end %>

        <% end %>
        

          <%= link_to "未分類", articles_path(current_category: "Unselected"), class: "list-group-item list-group-item-action" %>
          <%#= link_to "カテゴリ無し", articles_path %>

      </ul>
    </div>
    
    <!--記事一覧-->
    <div class="col-md-9 article-contents">
      <% @articles.each do |article| %>
        <div class="row border mb-1">
          <div class="col-md-2 eye-catch">
            <%= link_to (image_tag article.image_url(:thumb)), article_path(article)  %>
          </div>
          <div class="col-md-8 mt-1">
            <p>タイトル：<%= article.title %></p>
            <p>最終更新：<%= article.updated_at.to_s(:datetime_jp) %> 記事作成：<%= article.created_at.to_s(:datetime_jp) %></p>
            <p>カテゴリ：
              <% if article.category %>
                <%= article.category.name %>
              <% else %>
                未分類
              <% end %>
            </p>
          </div>
          
          <div class="col-md-2 edit-icon">
            <% if logged_in? %>
              <a href=<%= edit_article_path(article) %>><i class="fa fa-edit"></i> 編集</a><br>
              <%= link_to article, method: :delete, class: "ml-1", data: { confirm: '本当に削除してよろしいですか?' } do %>
                <i class="fa fa-trash"></i> 削除
              <% end %>
            <% end %>
          </div>
          
        </div><!--/row-->
      <% end %>
      <%= paginate @articles %>
    </div>
  </div>

</div>

app/views/articles/new.html.erb
<!-- articles/index.html.erb -->
<%= form_with(model: @article, local: true) do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>
  <div class="form-group">
    <div class="container w-100">
      <div id='editor'>
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <%= f.label :category_id, "カテゴリ" %>
              <%= f.collection_select(:category_id, @categories, :id, :name, :include_blank => "-未分類-") %>
            </div>
            
            <div class="form-group">
              <%= f.label :image, 'アイキャッチ画像' %>
              <%= f.file_field :image %>
            </div>
            
            <div class="form-group">
              <%= f.label :title, '記事タイトル' %>
              <%= f.text_field :title %>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6">
            <%= f.text_area :content, rows: 20, class: 'form-control', id: 'article_content', "v-model" => "input", name: "article[content]" %>
          </div>
          <div class="col-md-6">
            <div id="preview-field" class="content markdown-field" v-html="convertMarkdown"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%= link_to '記事一覧ページに戻る', articles_path, class: 'btn btn-secondary' %>
  <%= f.submit '新規記事作成', class: 'btn btn-primary' %>
  
<% end %>

<script>
  $(document).on('turbolinks:load', function() {
    
    // リアルタイムプレビュー
    new Vue({
      el: '#editor',// index.htmlでid="editor"となっている要素（エレメント）を指定
      data: {
        // index.htmlでv-model="input"が付与されている要素と双方向データバインディングされている。
        input: document.querySelector("[v-model='input']").value, 
      },
      computed: {
        convertMarkdown: function() {
          // index.htmlでv-html="convertMarkdown"が付与されている要素（エレメント）とバインディングされている。
          // 入力されたデータをHTMLに変換して表示させる。
          return marked(this.input);
        }
      }
    });
    
  });
</script>

app/views/articles/show.html.erb
<!-- articles/show.html.erb -->
<div class="container show-article">
  <div class="row mb-3">
    <div class="col-md-2">
      <%= image_tag @article.image_url(:thumb), class: "img-fluid", width: "40px", height: "25px" %>
      
    </div>
    <div class="col-md-10">
      <h3 class="article-title"><%= @article.title %></h3>
      <% if logged_in? %>
        <a href=<%= edit_article_path(@article) %>><i class="fa fa-edit"></i> 記事を編集</a>
      <% end %>
    </div>
  </div>

  <hr>
  
  <div class="markdown-field"><%= markdown(@article.content).html_safe %></div>

</div>

app/views/categories/new.html.erb
<!-- categories/new.html.erb -->
<%= form_with(model: @category, local: true) do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>

  <div class="form-group">
    <%= f.label :name, '新規カテゴリ名' %>
    <%= f.text_field :name %>
  </div>
  
  <%= link_to '記事一覧ページに戻る', articles_path, class: 'btn btn-secondary' %>
  
  <%= f.submit 'カテゴリ作成', class: 'btn btn-primary' %>
  
<% end %>

app/views/layouts/_admin_navbar.html.erb
<header class="mb-4">
  
  <nav class="navbar navbar-expand-lg navbar-light blog-navbar">
    <%= link_to 'Blog', articles_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to '記事作成', new_article_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to '新規カテゴリ作成', new_category_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'ログアウト', logout_path, method: :delete, class:"nav-link" %>
        </li>
      </ul>
      <span class="navbar-text">
        管理者用ナビゲーションバー
      </span>
    </div>
  </nav>  

</header>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark blog-navbar">
  <%= link_to 'Blog', articles_path, class:"navbar-brand" %>

</nav>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Portfolio Bootstrap 4 Template">
    <meta name="author" content="YoshihiroUto">

    <!-- Site Title -->
    <title>MyPortfolio</title>
    
    
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    
    <!-- Vue.js -->
    <!--<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>-->
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.min.js"></script>
    
    <!--マークダウン即時プレビュー用-->
    <script src='https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.5/marked.js'></script> 
    
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans:300,400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    
    

  </head>

  <!--body-->
  <body class='<%= controller.controller_name %>'>
    <!--ナビゲーションバー-->
    <header id="blog-site">
      <% url = request.fullpath %>
      <% if url != root_path and logged_in? %>
        <%= render 'layouts/admin_navbar' %>
      <% elsif url != root_path %>
        <%= render 'layouts/navbar' %>
      <% end %>
    </header>
    
    
    <%= render 'layouts/flash_messages' %>
    
    <%= yield %>
    

    <!-- Core JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <!-- / Core JavaScript -->
    
    <!-- preloader -->
    <!-- / preloader -->
    
    <!-- Smooth Scrolling -->
    <!-- / Smooth Scrolling -->
    
    <!-- menu-toggle Script -->
    <script>
      $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
      });
    </script>
    <!-- / menu-toggle Script -->
    
    <!-- Portfolio Script -->
    <script>
      $(document).ready(function(){
        if (Modernizr.touch) {
          // show the close overlay button
          $(".close-overlay").removeClass("hidden");
          // handle the adding of hover class when clicked
          $(".img").click(function(e){
            if (!$(this).hasClass("hover")) {
              $(this).addClass("hover");
            }
          });
          // handle the closing of the overlay
          $(".close-overlay").click(function(e){
            e.preventDefault();
            e.stopPropagation();
            if ($(this).closest(".img").hasClass("hover")) {
              $(this).closest(".img").removeClass("hover");
            }
          });
        } else {
          // handle the mouseenter functionality
          $(".img").mouseenter(function(){
            $(this).addClass("hover");
          })
          // handle the mouseleave functionality
          .mouseleave(function(){
            $(this).removeClass("hover");
          });
        }
      });
    </script>
    <!-- / Portfolio Script -->
    
    <!-- contact form -->
    <!-- / contact form -->
    
    <!-- Hide Nav -->
    <!-- / Hide Nav -->

  </body>
  

</html>